Schema: factory-2019-04-01
Portfolios: []
Products:
  - Name: "compliant-bucket"
    Owner: "data-governance@acme.com"
    Description: "Creates an AWS S3 Bucket that meets data-governance standards"
    Distributor: "cloud-engineering"
    SupportDescription: "Speak to data-governance@acme.com about exceptions and speak to cloud-engineering@acme.com about implementation issues"
    SupportEmail: "cloud-engineering@acme.com"
    SupportUrl: "https://wiki.acme.com/cloud-engineering/governance/compliant-bucket"
    Tags:
      - Key: "type"
        Value: "governance"
      - Key: "creator"
        Value: "cloud-engineering"
      - Key: "cost-center"
        Value: "cloud-engineering"
    Versions:
      - Name: "v1"
        Description: "v1 of compliant-bucket"
        Active: True
        Source:
          Provider: "CodeCommit"
          Configuration:
            RepositoryName: "compliant-bucket"
            BranchName: "master"
