Schema: factory-2019-04-01
Portfolios: []
Products:
  - Name: "compliant-bucket"
    Owner: "data-governance@acme.com"
    Description: "Will provision an AWS S3 bucket that meets data-governance standards"
    Distributor: "cloud-engineering"
    SupportDescription: "Speak to data-governance@acme.com about exceptions and speak to cloud-engineering@acme.com about implementation issues"
    SupportEmail: "cloud-engineering@acme.com"
    SupportUrl: "https://wiki.acme.com/cloud-engineering/governance/compliant-bucket"
    Tags:
      - Key: "type"
        Value: "governance"
      - Key: "creator"
        Value: "cloud-engineering"
      - Key: "cost-center"
        Value: "cloud-engineering"