Schema: factory-2019-04-01
Products:
  - Name: "aws-config-s3-bucket-server-side-encryption-enabled"
    Owner: "data-governance@acme.com"
    Description: "Enables the AWS Config managed rule s3-bucket-server-side-encryption-enabled"
    Distributor: "cloud-engineering"
    SupportDescription: "Speak to data-governance@acme.com about exceptions and speak to cloud-engineering@acme.com about implementation issues"
    SupportEmail: "cloud-engineering@acme.com"
    SupportUrl: "https://wiki.acme.com/cloud-engineering/governance/aws-config-s3-bucket-server-side-encryption-enabled"
    Tags:
      - Key: "type"
        Value: "governance"
      - Key: "creator"
        Value: "cloud-engineering"
      - Key: "cost-center"
        Value: "cloud-engineering"
    Versions:
      - Name: v1
        Description: "v1 of aws-config-s3-bucket-server-side-encryption-enabled"
        Active: True
        Source:
          Provider: CodeCommit
          Configuration:
            RepositoryName: aws-config-s3-bucket-server-side-encryption-enabled
            BranchName: master
